{
[1]={ "Lorem ipsum dolor   ",
      "sit amet,           ",
      "consectetur         ",
      "adipiscing elit.    ",
      "Phasellus eget diam ",
      "placerat, viverra   ",
      "tellus vulputate,   ",
      "feugiat lectus.     ",
},
[2]={ "Nullam fermentum,   ",
      "lacus et sodales    ",
      "iaculis, ipsum mi,  ",
      "eu semper nisl dui  ",
      "quis turpis. Cras   ",
      "vel est tempor,     ",
      "dignissim metus     ",
      "vitae, volutpat     ",
},
[3]={ "diam. Vestibulum    ",
      "elementum mauris    ",
      "eget ex venenatis,  ",
      "in ultrices elit    ",
      "eleifend. Morbi ut  ",
      "egestas risus, vitae",
      "elementum mi.       ",
      "                    ",
},
}